apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: default # this is the scope where the role applies
  labels:  
    kubernetes.courselabs.co: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]