apiVersion: v1
kind: Secret
metadata:
  name: todo-list-secret
  labels:
    kubernetes.courselabs.co: operators
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {
        "ToDoDb": "server=todo-db-mysql;database=todo;user=root;password=op3rtor1ab$"
      }
    }