apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-list-config
  labels:
    kubernetes.courselabs.co: operators
data:
  config.json: |-
    {
      "Database" : {
        "Provider" : "MySql"
      },
      "MessageQueue": {
        "Url": "nats://todo-list-queue:4222"
      }
    }