id=Y:ID
name=Y:Name
automobile[*].make=Y:Make
automobile[*].fuelType=Y:Fuel Type
passport.number=Y:psprt_nbr
passport.country=Y:psprt_ctry
passport.expiry=Y:psrprt_expiry
address.city=Y:City
address.zip=Y:ZIP
address.locations[*].type=Y:Location Type
address.locations[*].zip=Y:Location ZIP
address.locations[*].metadata.isPrimary=Y:Is Primary
address.locations[*].metadata.contacts[*].phone=Y:Phone
address.locations[*].metadata.contacts[*].email=Y:Email
address.locations[*].metadata.contacts[*].social[*].platform=Y:Social Platform
address.locations[*].metadata.contacts[*].social[*].handle=Y:Social Handle