apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http    
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.serviceNodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}
    component: server
  type: {{ .Values.serviceType }}