apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-approve-csr
  labels:
    kubernetes.courselabs.co: rbac
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "patch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups:  ["certificates.k8s.io"]
  resources:  ["signers"]
  resourceNames:  ["kubernetes.io/kube-apiserver-client", "kubernetes.io/legacy-unknown"]
  verbs: ["approve"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-cert-generator
  labels:
    kubernetes.courselabs.co: rbac
subjects:
- kind: ServiceAccount
  name: user-cert-generator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-approve-csr
