apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    kubernetes.courselabs.co: rollouts
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-statefulset
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.18-alpine
          name: nginx
