apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  destination:
    namespace: whoami
    server: https://kubernetes.default.svc
  project: default
  source:
    path: labs/argo/project/helm/whoami
    repoURL: http://gogs.infra.svc.cluster.local:3000/kiamol/kiamol.git
  syncPolicy:
    automated: 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true