apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-account-viewer
  namespace: default # this is the scope where the role applies
  labels:  
    kubernetes.courselabs.co: rbac
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-explorer-service-account-viewer
  namespace: default # needs to match the ns in the role
  labels:  
    kubernetes.courselabs.co: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-account-viewer
subjects:
- kind: ServiceAccount
  name: kube-explorer
  namespace: default # the subject can be in a different ns