apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:  
    kubernetes.courselabs.co: rbac
spec:  
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        sa-token: none
    spec:
      automountServiceAccountToken: false
      containers:
        - name: sleep
          image: kiamol/ch03-sleep