apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: configurable-cpu
  labels:
    kubernetes.courselabs.co: productionizing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: configurable
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
