AWSTemplateFormatVersion: "2010-09-09"

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

Description: >
  This template builds a jump host in a private subnet, equipped with Session Manager for connections.
  It will have security group connectivity to a DocumentDB cluster.

Parameters:
  InstanceSize:
    Type: String
    Description: Instance size
    # Default: "m5.8xlarge"
    Default: "t2.micro"
  SubnetPrivate:
    Type: "AWS::EC2::Subnet::Id"
  ProjectTag:
    Type: String
  VolumeSize:
    Type: Number
    # Default: 100
    Default: 10
  ClientFirewall:
    Type: AWS::EC2::SecurityGroup::Id
  VPC:
    Type: "AWS::EC2::VPC::Id"

Mappings:
  RegionMap:
    us-east-1:
      # "AMALINUX" : "ami-062f7200baf2fa504"
      "AMALINUX" : "ami-0889a44b331db0194"
    us-west-2:
      "AMALINUX" : "ami-04590e7389a6e577c"
Resources:

  EgressFirewall:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Join ["", ["Stack ", !Ref "AWS::StackId", " Egress"]]
      VpcId: !Ref VPC
      SecurityGroupEgress:
        -
          CidrIp: 0.0.0.0/0
          ToPort: "-1"
          IpProtocol: "-1"
  JumpServer:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !Ref InstanceSize
      IamInstanceProfile: !Ref SsmInstanceProfile
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: !Ref VolumeSize
      SubnetId:
        Ref: SubnetPrivate
      SecurityGroupIds:
        - !Ref EgressFirewall
        - !Ref ClientFirewall
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Name
          Value: JumpHost

  SsmInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "SsmRole"

  SsmRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
Outputs:
  JumpAddress:
    Description: Instance ID of jump host
    Value: !Ref JumpServer
