# -*- coding: utf-8 -*-
"""0_text_classification_by_xgboost_others_using_bbc_news_articles_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0zqTPT2tO99M0swYgWxfU-HjN5-DPUk

# Text Classification by XGBoost & Others

https://pub.towardsai.net/text-classification-by-xgboost-others-a-case-study-using-bbc-news-articles-5d88e94a9f8

This example is a 5-class classification

## 1.0 - Getting the data
"""

import pandas as pd

bbc_text_df = pd.read_csv('bbc-text.csv')
bbc_text_df.head()

bbc_text_df.shape

"""## 2.0 Text Cleaning

In this example, we will use use Python ‘gensim’ library for all text cleaning
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install gensim

from gensim import utils
import gensim.parsing.preprocessing as gsp

filters = [
    gsp.strip_tags,
    gsp.strip_punctuation,
    gsp.strip_multiple_whitespaces,
    gsp.strip_numeric,
    gsp.remove_stopwords,
    gsp.strip_short,
    gsp.stem_text
]


def clean_text(s):
    s = s.lower()
    s = utils.to_unicode(s)
    for f in filters:
        s = f(s)
    return s

df_x = bbc_text_df['text']
df_y = bbc_text_df['category']

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_y_encoded = le.fit_transform(df_y)

print(le.classes_)

df_x = df_x.apply(clean_text)

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(df_x, df_y_encoded, test_size = 0.2, stratify=df_y_encoded, random_state = 42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size = 0.5, stratify=y_temp, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    max_features=50000,        # limit dimensionality (adjust to your RAM)
    ngram_range=(1, 2),        # capture unigrams + bigrams
    min_df=2,                  # ignore rare words appearing in <2 docs
    max_df=0.9,                # drop overly common words appearing in >90% of docs
    sublinear_tf=True,         # use log-scaling on term frequency
    norm="l2",                 # normalize each row vector
)

Xtr = tfidf.fit_transform(X_train)
Xva = tfidf.transform(X_val)
Xte = tfidf.transform(X_test)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)
class_to_weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
sample_weights = np.array([class_to_weights[c] for c in y_train])

from xgboost import XGBClassifier

clf = XGBClassifier(
    n_estimators=50,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="mlogloss"
)

clf.fit(Xtr, y_train, sample_weight=sample_weights, eval_set=[(Xva, y_val)], verbose=True)

from sklearn.metrics import accuracy_score, classification_report

# Make predictions on the test set
y_pred = clf.predict(Xte)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=[str(c) for c in le.classes_]))

"""## 4.0 Sample Predictions"""

# Example of a new text
sample_text = "The stock market experienced a significant downturn today, with major indices falling sharply due to concerns over inflation."

# Clean and transform the sample text using the same functions and vectorizer
cleaned_sample_text = clean_text(sample_text)
transformed_sample_text = tfidf.transform([cleaned_sample_text]) # tfidf expects an iterable

# Make a prediction
predicted_label_encoded = clf.predict(transformed_sample_text)

print(le.classes_)

# Decode the predicted label back to the original category name
predicted_category = le.inverse_transform(predicted_label_encoded)

print(f"Sample Text: {sample_text}")
print(f"Predicted Category: {predicted_category[0]}")