apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb
  labels: 
    kubernetes.courselabs.co: rollouts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vweb
    spec:
      containers:
        - name: web
          image: kiamol/ch09-vweb:v3
          ports:
            - name: http
              containerPort: 80

