apiVersion: v1
kind: ConfigMap
metadata:
  name: configurable-env
  labels: 
    kubernetes.courselabs.co: secrets
    app: configurable
data:
  Configurable__Release: from-configmap
  Configurable__Extra: from-configmap