apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
    kubernetes.courselabs.co: secrets
    app: configurable
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04  
          env:
            - name: Configurable__Environment
              value: from-podspec
          envFrom:          
            - configMapRef:
                name: configurable-env
            - secretRef:
                name: configurable-env-plain
