apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  labels:
    kubernetes.courselabs.co: operators
type: Opaque
stringData:
  ROOT_PASSWORD: op3rtor1ab$
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: todo-db
spec:
  image: percona:5.7.35
  replicas: 1
  secretName: todo-db-secret  
  podSpec:    
    resources:
      limits:
        memory: 200Mi
        cpu: 200m