apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
    kubernetes.courselabs.co: secrets
    app: configurable
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04         
          envFrom:
            - secretRef:
                name: configurable-env-file
          volumeMounts:
            - name: secret
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: secret
          secret: 
            secretName: configurable-secret-file
