apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  labels:
    kubernetes.courselabs.co: productionizing
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  labels:
    kubernetes.courselabs.co: productionizing
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
  type: LoadBalancer