
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=Oracle123
batch.param1=DevName
logging.file.name=logs/dev-app.log
logging.file.max-size=10MB
logging.file.total-size-cap=100MB
