
spring.datasource.url=jdbc:oracle:thin:@prod-db-host:1521/PRODDB
spring.datasource.username=prod_user
spring.datasource.password=prod_password
batch.param1=ProdName
logging.file.name=logs/prod-app.log
logging.file.max-size=10MB
logging.file.total-size-cap=100MB
