AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Elastic Serverless Forwarder

  Send observability data from your AWS environment to Elastic.

Parameters:
  ElasticServerlessForwarderS3ConfigFile:
    Type: String
    Default: "s3://"
    Description: S3 URL of the config yaml file (to be set as `S3_CONFIG_FILE` env variable)
  ElasticServerlessForwarderSSMSecrets:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of AWS SSM Secrets ARNs referenced in the config yaml file
  ElasticServerlessForwarderKMSKeys:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of AWS KMS Keys ARNs to be used for decrypting AWS SSM Secrets referenced in the config yaml file
  ElasticServerlessForwarderSQSEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Direct SQS queues ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderSQSEvents2:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Direct SQS queues ARNs to set as event triggers for the Lambda, if limit is reached on ElasticServerlessForwarderSQSEvents
  ElasticServerlessForwarderS3SQSEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of S3 SQS Event Notifications ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderS3SQSEvents2:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of S3 SQS Event Notifications ARNs to set as event triggers for the Lambda, if limit is reached on ElasticServerlessForwarderS3SQSEvents
  ElasticServerlessForwarderKinesisEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Kinesis Data Stream ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderKinesisEvents2:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Kinesis Data Stream ARNs to set as event triggers for the Lambda, if limit is reached on ElasticServerlessForwarderKinesisEvents
  ElasticServerlessForwarderCloudWatchLogsEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Cloudwatch Logs Log Groups ARNs to set subscription filters on the Lambda for
  ElasticServerlessForwarderCloudWatchLogsEvents2:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Cloudwatch Logs Log Groups ARNs to set subscription filters on the Lambda for, if limit is reached on ElasticServerlessForwarderCloudWatchLogsEvents
  ElasticServerlessForwarderS3Buckets:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of S3 buckets ARNs that are the sources of the S3 SQS Event Notifications
  ElasticServerlessForwarderSecurityGroups:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of the security group IDs to attach to the Lambda
  ElasticServerlessForwarderSubnets:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of the subnet IDs the Lambda should belong to
Resources:
  ElasticServerlessForwarderEventMacro:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:%awsOrGov%:serverlessrepo:%awsRegion%:%accountID%:applications/helper-macro-%sarAppName%
        SemanticVersion: %semanticVersion%
  ElasticServerlessForwarderApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:%awsOrGov%:serverlessrepo:%awsRegion%:%accountID%:applications/helper-application-%sarAppName%
        SemanticVersion: %semanticVersion%
      Parameters:
        ElasticServerlessForwarderS3ConfigFile: !Ref ElasticServerlessForwarderS3ConfigFile
        ElasticServerlessForwarderSSMSecrets: !Join [",", !Ref ElasticServerlessForwarderSSMSecrets]
        ElasticServerlessForwarderKMSKeys: !Join [",", !Ref ElasticServerlessForwarderKMSKeys]
        ElasticServerlessForwarderSQSEvents: !Join [",", !Ref ElasticServerlessForwarderSQSEvents]
        ElasticServerlessForwarderSQSEvents2: !Join [",", !Ref ElasticServerlessForwarderSQSEvents2]
        ElasticServerlessForwarderS3SQSEvents: !Join [",", !Ref ElasticServerlessForwarderS3SQSEvents]
        ElasticServerlessForwarderS3SQSEvents2: !Join [",", !Ref ElasticServerlessForwarderS3SQSEvents2]
        ElasticServerlessForwarderKinesisEvents: !Join [",", !Ref ElasticServerlessForwarderKinesisEvents]
        ElasticServerlessForwarderKinesisEvents2: !Join [",", !Ref ElasticServerlessForwarderKinesisEvents2]
        ElasticServerlessForwarderCloudWatchLogsEvents: !Join [",", !Ref ElasticServerlessForwarderCloudWatchLogsEvents]
        ElasticServerlessForwarderCloudWatchLogsEvents2: !Join [",", !Ref ElasticServerlessForwarderCloudWatchLogsEvents2]
        ElasticServerlessForwarderS3Buckets: !Join [",", !Ref ElasticServerlessForwarderS3Buckets]
        ElasticServerlessForwarderSecurityGroups: !Join [",", !Ref ElasticServerlessForwarderSecurityGroups]
        ElasticServerlessForwarderSubnets: !Join [",", !Ref ElasticServerlessForwarderSubnets]
    DependsOn: ElasticServerlessForwarderEventMacro
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Elastic Serverless Forwarder Configuration options
        Parameters:
          - ElasticServerlessForwarderS3ConfigFile
          - ElasticServerlessForwarderSSMSecrets
          - ElasticServerlessForwarderKMSKeys
      - Label:
          default: Elastic Serverless Forwarder Events options
        Parameters:
          - ElasticServerlessForwarderSQSEvents
          - ElasticServerlessForwarderSQSEvents2
          - ElasticServerlessForwarderS3SQSEvents
          - ElasticServerlessForwarderS3SQSEvents2
          - ElasticServerlessForwarderKinesisEvents
          - ElasticServerlessForwarderKinesisEvents2
          - ElasticServerlessForwarderCloudWatchLogsEvents
          - ElasticServerlessForwarderCloudWatchLogsEvents2
      - Label:
          default: Elastic Serverless Forwarder S3 Buckets Permissions options
        Parameters:
          - ElasticServerlessForwarderS3Buckets
      - Label:
          default: Elastic Serverless Forwarder Network options
        Parameters:
          - ElasticServerlessForwarderSecurityGroups
          - ElasticServerlessForwarderSubnets
    ParameterLabels:
      ElasticServerlessForwarderS3ConfigFile:
        default: "Config File"
      ElasticServerlessForwarderSSMSecrets:
        default: "AWS SSM Secrets"
      ElasticServerlessForwarderKMSKeys:
        default: "AWS KMS Keys"
      ElasticServerlessForwarderCloudWatchLogsEvents:
        default: "Cloudwatch Logs subscription filters"
      ElasticServerlessForwarderCloudWatchLogsEvents2:
        default: "Cloudwatch Logs subscription filters, if limit is reached on ElasticServerlessForwarderCloudWatchLogsEvents"
      ElasticServerlessForwarderKinesisEvents:
        default: "Kinesis Data Stream event triggers"
      ElasticServerlessForwarderKinesisEvents2:
        default: "Kinesis Data Stream event triggers, if limit is reached on ElasticServerlessForwarderKinesisEvents"
      ElasticServerlessForwarderS3SQSEvents:
        default: "S3 SQS Event Notifications event triggers"
      ElasticServerlessForwarderS3SQSEvents2:
        default: "S3 SQS Event Notifications event triggers, if limit is reached on ElasticServerlessForwarderS3SQSEvents"
      ElasticServerlessForwarderSQSEvents:
        default: "Direct SQS queues event triggers"
      ElasticServerlessForwarderSQSEvents2:
        default: "Direct SQS queues event triggers, if limit is reached on ElasticServerlessForwarderSQSEvents"
      ElasticServerlessForwarderS3Buckets:
        default: "S3 buckets of S3 SQS Event Notifications"
      ElasticServerlessForwarderSecurityGroups:
        default: "Security groups to attach to the Elastic Serverless Forwarder"
      ElasticServerlessForwarderSubnets:
        default: "Subnets for the Elastic Serverless Forwarder"
  AWS::ServerlessRepo::Application:
    Name: %sarAppName%
    Description: Send observability data from your AWS environment to Elastic.
    Author: %sarAuthorName%
    Labels: ['s3', 'logs', 'analytics', 'observability', 'monitoring', 'Elastic']
    SemanticVersion: %semanticVersion%
    LicenseUrl: %codeUri%/LICENSE.txt
    ReadmeUrl: %codeUri%/README.md
    HomePageUrl: https://github.com/elastic/elastic-serverless-forwarder
    SourceCodeUrl: https://github.com/elastic/elastic-serverless-forwarder
Outputs:
  EsfLambdaFunctionARN:
    Description: ARN of the ESF Lambda Function
    Value: !GetAtt ElasticServerlessForwarderApplication.Outputs.EsfLambdaFunctionARN
  EsfLambdaFunctionRoleARN:
      Description: The name of ESF Lambda Function
      Value: !GetAtt ElasticServerlessForwarderApplication.Outputs.EsfLambdaFunctionRoleARN
