
# -------------------------------------------
# Control missing value placeholders in output
# Options:
#   csv.missing.value=NaN      # Default
#   csv.missing.value=         # Blank cell
#   csv.missing.value=null     # Literal 'null'
#   csv.missing.value=N/A      # Custom placeholder
# -------------------------------------------

id=Y:ID
name=Y:Name
automobile[*].make=Y:Make
automobile[*].fuelType=Y:Fuel Type
PASS_PRT.N_UMBER=Y:Passport Number
PASS_PRT.C_OUNTRY=Y:Passport Country
PASS_PRT.E_XPIRY=Y:Passport Expiry
address.city=Y:City
address.zip=Y:ZIP
address.locations[*].type=Y:Location Type
address.locations[*].zip=Y:Location ZIP
address.locations[*].metadata.isPrimary=Y:Is Primary
address.locations[*].metadata.contacts[*].phone=Y:Phone
address.locations[*].metadata.contacts[*].email=Y:Email
address.locations[*].metadata.contacts[*].social[*].platform=Y:Social Platform
address.locations[*].metadata.contacts[*].social[*].handle=Y:Social Handle

# Value used for missing fields
csv.missing.value=NaN

csv.include.position.header=true