apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: web
      slot: blue
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: web
        slot: blue
    spec:
      containers:
        - name: app
          image: {{ .Values.blueImage }}
          ports:
            - name: http
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-green
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: web
      slot: green
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: web
        slot: green
    spec:
      containers:
        - name: app
          image: {{ .Values.greenImage }}
          ports:
            - name: http
              containerPort: 80
