apiVersion: v1
kind: Service
metadata:
  name: fulfilment-api-lb
  labels: 
    kubernetes.courselabs.co: logging
spec:
  selector:
    app: fulfilment
    component: api
  ports:
  - port: 8011
    targetPort: http
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: fulfilment-api-np
  labels: 
    kubernetes.courselabs.co: logging
spec:
  selector:
    app: fulfilment
    component: api
  ports:
  - port: 8011
    targetPort: http
    nodePort: 30018
  type: NodePort