apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-edit-default
  namespace: default # this is the scope where the binding applies
  labels:
    kubernetes.courselabs.co: rbac
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: reader@courselabs.co
  apiGroup: rbac.authorization.k8s.io