apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-one
  labels:
    kubernetes.courselabs.co: jobs
    app: pi-one 
    dp: '500'       
spec:
  template:
    spec:
      containers:
        - name: pi
          image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "console", "-dp", "500"]
      restartPolicy: Never
