apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    kubernetes.courselabs.co: rollouts
spec:
  ports:
    - port: 8010
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    kubernetes.courselabs.co: rollouts
spec:
  ports:
    - port: 8010
      targetPort: 80
      nodePort: 30010
  selector:
    app: nginx
  type: NodePort