spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLCDB
spring.datasource.username=your_user
spring.datasource.password=your_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=BatchJobPool

# Monitoring
management.endpoints.web.exposure.include=health,info,metrics

# Logs folder
logging.file.name=logs/batch.log


# Prometheus endpoint
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
