apiVersion: v1
kind: Service
metadata:
  name: configurable-np
  namespace: configurable
  labels:
    kubernetes.courselabs.co: namespaces
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8020
      targetPort: 80
      nodePort: 30020
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: configurable-lb
  namespace: configurable
  labels:
    kubernetes.courselabs.co: namespaces
spec:
  selector:
    app: configurable
  ports:
    - name: http
      port: 8020
      targetPort: 80
  type: LoadBalancer