apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader 
  labels:
    kubernetes.courselabs.co: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]