apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: students.kubernetes.courselabs.co
  labels:
    kubernetes.courselabs.co: operators
spec:
  group: kubernetes.courselabs.co
  scope: Namespaced
  names:
    plural: students
    singular: student
    kind: Student
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                email:
                  type: string
                company:
                  type: string
      additionalPrinterColumns:
        - name: Email
          type: string
          description: Email Address
          jsonPath: .spec.email
        - name: Company
          type: string
          description: Company
          jsonPath: .spec.company
