apiVersion: v1
kind: Service
metadata:
  name: hello-web-np
  labels:
    kubernetes.courselabs.co: affinity
spec:
  selector:
    app: hello-web
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30781
  type: NodePort