apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}
  labels:
    app.kubernetes.io/component: orchestrator-raft
    {{- include "mysql-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: raft
      port: 10008
      targetPort: 10008
  selector:
    {{- include "mysql-operator.selectorLabels" . | nindent 4 }}
