spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  data:
    mongodb:
      uri: mongodb://localhost:27017/appdb
      database: appdb

app:
  s3:
    bucket: your-bucket-name
    prefix: etl/exports
  etl:
    oracle-query: "SELECT EMP_ID, FIRST_NAME, LAST_NAME, EMAIL FROM EMPLOYEES FETCH FIRST 5 ROWS ONLY"
    mongo-collection: employees
