# src: [Building event-driven architectures on AWS](https://catalog.us-east-1.prod.workshops.aws/workshops/63320e83-6abc-493d-83d8-f822584fb3cb/en-US)
---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Master stack: AWS Event-driven Architectures Workshop"

Resources:
  CognitoUserPool:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://aws-event-driven-architecture-workshop-assets.s3.amazonaws.com/cognito-user-pool-v2.yaml
      TimeoutInMinutes: 60

  SNS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://aws-event-driven-architecture-workshop-assets.s3.amazonaws.com/sns-v2.yaml
      TimeoutInMinutes: 60

  EventBridge:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://aws-event-driven-architecture-workshop-assets.s3.amazonaws.com/event-bridge-v2.yaml
      TimeoutInMinutes: 60

  Lambda:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: https://aws-event-driven-architecture-workshop-assets.s3.amazonaws.com/lambda-v2.yaml
      TimeoutInMinutes: 60

Outputs:
  StackRef:

    Value: !Ref CognitoUserPool

  WildRydesSaasPlaygroundConfigurationUrl:
    Description: Wild Rydes Saas Playground configuration link
    Value: !GetAtt CognitoUserPool.Outputs.WildRydesSaasPlaygroundConfigurationUrl

  CognitoUsername:
    Description: Cognito username for use with Wild Rydes SaaS Playground
    Value: !GetAtt CognitoUserPool.Outputs.CognitoUsername

  CognitoPassword:
    Description: Cognito password for use with Wild Rydes SaaS Playground
    Value: !GetAtt CognitoUserPool.Outputs.CognitoPassword

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt EventBridge.Outputs.ApiUrl
