apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  labels:
    kubernetes.courselabs.co: affinity
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30780
  type: NodePort