---
## Workflow to push zip with dependencies to S3 bucket every time the ESF version is updated
name: upload-dependencies

env:
  BUCKET_NAME : "esf-dependencies"
  AWS_REGION : "eu-central-1"
  ROLE: "arn:aws:iam::267093732750:role/esf-dependencies-role"


on:
  workflow_run:
    workflows: [release]
    types:
      - completed


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout


jobs:

  build-and-upload-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # See https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-dependencies

      - uses: actions/checkout@v4

      - name: Get version number
        shell: bash
        run: |
          VERSION=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+(\-[a-zA-Z]+[0-9]+)?' share/version.py)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::notice::ESF version is $VERSION."

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'          # caching pip dependencies

      - name: Install requirements in a directory and zip it.
        shell: bash
        run: |
          pip3 install -r requirements.txt -t ./dependencies
          cd dependencies && zip -r ../lambda-v${{ env.VERSION }}.zip .

      - name: Place handlers in the zip file.
        shell: bash
        run: |
          zip -r ./lambda-v${{ env.VERSION }}.zip main_aws.py
          zip -r ./lambda-v${{ env.VERSION }}.zip handlers
          zip -r ./lambda-v${{ env.VERSION }}.zip share
          zip -r ./lambda-v${{ env.VERSION }}.zip storage
          zip -r ./lambda-v${{ env.VERSION }}.zip shippers

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy file to s3
        run: |
          aws s3 cp ./lambda-v${{ env.VERSION }}.zip s3://${{ env.BUCKET_NAME }}/

