apiVersion: v1
kind: Service
metadata:
  name: apod-log
  namespace: apod
spec:
  ports:
    - port: 80
      targetPort: api
  selector:
    app: apod-log
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-log
  namespace: apod
spec:
  selector:
    matchLabels:
      app: apod-log
      version: v1
  template:
    metadata:
      labels:
        app: apod-log
        version: v1
    spec:
      containers:
        - name: api
          image: kiamol/ch14-access-log
          ports:
            - containerPort: 80
              name: api
          resources:
            limits:
              cpu: 250m
              memory: 200Mi

