apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: whoami
  labels:
    kubernetes.courselabs.co: namespaces
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-np
  namespace: whoami
  labels:
    kubernetes.courselabs.co: namespaces
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 8010
      targetPort: 80
      nodePort: 30010
  type: NodePort