apiVersion: v1
kind: Pod
metadata:
  name: buildkit-cli
  labels:
    kubernetes.courselabs.co: buildkit
spec:
  containers:
    - name: buildkitd
      image: moby/buildkit:v0.9.0
      envFrom:
        - configMapRef:
            name: build-config
      volumeMounts:
        - name: registry-creds
          mountPath: /root/.docker
          readOnly: true
  volumes:
    - name: registry-creds
      secret:
        secretName: registry-creds
        defaultMode: 0400
        items:
          - key: .dockerconfigjson
            path: config.json
