apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    kubernetes.courselabs.co: affinity
spec:
  replicas: 6
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: app
          image: sixeyed/whoami:21.04
      nodeSelector:
        kubernetes.io/os: linux
        # you can only express equality in a node selector
        # you can't say a label shouldn't exist or
        # should not have a specific value
        # node-role.kubernetes.io/control-plane: !true
        